version: "3.7"

services:
  nginx-proxy:
    container_name: nginx 
    image: nginx:1.21     
    volumes:              
      - /etc/nginx/:/etc/nginx/:ro
    ports: 
      - "80:80"
      - "443:443"
    restart: always