version: "3.7"

services:
  nginx-proxy:
    container_name: nginx 
    image: nginx:1.21     
    volumes:              
      - /var/log/nginx:/var/log/nginx
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/:/etc/nginx/ssl:ro
    ports: 
      - "80:80"
      - "443:443"
    restart: always