version: "3.7"

services:
  nginx-proxy:
    container_name: nginx 
    image: nginx:1.21     
    volumes:              
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/nginx-proxy-server.ru/:/etc/ssl/:ro
    ports: 
      - "80:80"
      - "443:443"
    restart: always